import 'package:flutter/material.dart';
import 'dnd_class.dart';
import 'hero_ability.dart';

class AbilityRune {
  const AbilityRune({
    required this.id,
    required this.name,
    required this.classRequired,
    required this.abilityId,
    required this.icon,
    required this.color,
    required this.description,
    required this.dustCost,
    this.valueMult = 1.0,
    this.durationAdd = 0,
    this.cooldownReduce = 0,
    this.effectOverride,
    this.bonusEffectDesc,
  });

  final String id, name, abilityId, icon, description;
  final DndClass classRequired;
  final Color color;
  final int dustCost;
  final double valueMult;
  final int durationAdd;
  final int cooldownReduce;
  final AbilityEffect? effectOverride;
  final String? bonusEffectDesc;

  static const all = <AbilityRune>[
    // ── BARBARIAN ───────────────────────────────────────────────────────────
    AbilityRune(id: 'barb_rune_1', name: 'Rune of Bloodrage', classRequired: DndClass.barbarian,
      abilityId: 'barb_0', icon: '🩸', color: Color(0xFFcc2222), dustCost: 15,
      valueMult: 1.5, bonusEffectDesc: 'Rage Strike deals 50% more damage',
      description: 'Infuse Rage Strike with blood magic — 50% more damage.'),
    AbilityRune(id: 'barb_rune_2', name: 'Rune of Undying', classRequired: DndClass.barbarian,
      abilityId: 'barb_3', icon: '💀', color: Color(0xFFff6644), dustCost: 20,
      durationAdd: 2, cooldownReduce: 2, bonusEffectDesc: 'War Cry lasts 2 extra rounds, -2 cooldown',
      description: 'War Cry echoes longer — +2 duration, −2 cooldown.'),

    // ── FIGHTER ─────────────────────────────────────────────────────────────
    AbilityRune(id: 'ftr_rune_1', name: 'Rune of Precision', classRequired: DndClass.fighter,
      abilityId: 'ftr_0', icon: '🎯', color: Color(0xFF88aadd), dustCost: 15,
      valueMult: 1.4, bonusEffectDesc: 'Power Strike deals 40% more damage',
      description: 'Sharpen Power Strike — 40% more damage.'),
    AbilityRune(id: 'ftr_rune_2', name: 'Rune of the Bulwark', classRequired: DndClass.fighter,
      abilityId: 'ftr_2', icon: '🛡', color: Color(0xFF6688ff), dustCost: 20,
      durationAdd: 3, bonusEffectDesc: 'Second Wind heals over 3 extra rounds',
      description: 'Second Wind becomes a sustained heal — +3 duration.'),

    // ── ROGUE ───────────────────────────────────────────────────────────────
    AbilityRune(id: 'rog_rune_1', name: 'Rune of Shadows', classRequired: DndClass.rogue,
      abilityId: 'rog_0', icon: '🌑', color: Color(0xFF44cc88), dustCost: 15,
      valueMult: 1.6, cooldownReduce: 1, bonusEffectDesc: 'Backstab deals 60% more, -1 cooldown',
      description: 'Strike from deeper shadow — 60% more damage, −1 cooldown.'),
    AbilityRune(id: 'rog_rune_2', name: 'Rune of Vanishing', classRequired: DndClass.rogue,
      abilityId: 'rog_3', icon: '💨', color: Color(0xFF66ddaa), dustCost: 20,
      durationAdd: 2, bonusEffectDesc: 'Evasion lasts 2 extra rounds',
      description: 'Vanish into mist — Evasion extended by 2 rounds.'),

    // ── RANGER ──────────────────────────────────────────────────────────────
    AbilityRune(id: 'rng_rune_1', name: 'Rune of the Hunt', classRequired: DndClass.ranger,
      abilityId: 'rng_0', icon: '🏹', color: Color(0xFF66aa44), dustCost: 15,
      valueMult: 1.5, bonusEffectDesc: 'Aimed Shot deals 50% more damage',
      description: 'The perfect shot — 50% more damage.'),
    AbilityRune(id: 'rng_rune_2', name: 'Rune of Thorns', classRequired: DndClass.ranger,
      abilityId: 'rng_2', icon: '🌿', color: Color(0xFF88cc44), dustCost: 20,
      durationAdd: 3, valueMult: 1.3, bonusEffectDesc: 'Poison Shot: +30% damage, +3 duration',
      description: 'Venom-tipped arrows burn longer — +30% damage, +3 DoT rounds.'),

    // ── PALADIN ─────────────────────────────────────────────────────────────
    AbilityRune(id: 'pal_rune_1', name: 'Rune of Radiance', classRequired: DndClass.paladin,
      abilityId: 'pal_0', icon: '✦', color: Color(0xFFffcc33), dustCost: 15,
      valueMult: 1.5, bonusEffectDesc: 'Smite deals 50% more damage',
      description: 'Holy light intensifies — Smite deals 50% more.'),
    AbilityRune(id: 'pal_rune_2', name: 'Rune of Devotion', classRequired: DndClass.paladin,
      abilityId: 'pal_2', icon: '💛', color: Color(0xFFffee66), dustCost: 20,
      valueMult: 1.4, durationAdd: 2, bonusEffectDesc: 'Lay on Hands: +40% heal, +2 regen rounds',
      description: 'Deeper faith — 40% stronger heal with extended regen.'),

    // ── CLERIC ──────────────────────────────────────────────────────────────
    AbilityRune(id: 'clr_rune_1', name: 'Rune of Grace', classRequired: DndClass.cleric,
      abilityId: 'clr_1', icon: '❤', color: Color(0xFFff88aa), dustCost: 15,
      valueMult: 1.5, bonusEffectDesc: 'Heal Word restores 50% more HP',
      description: 'Divine grace amplifies healing — +50% HP restored.'),
    AbilityRune(id: 'clr_rune_2', name: 'Rune of Sanctuary', classRequired: DndClass.cleric,
      abilityId: 'clr_3', icon: '🛡', color: Color(0xFFffddaa), dustCost: 20,
      durationAdd: 3, bonusEffectDesc: 'Shield of Faith lasts 3 extra rounds',
      description: 'Sacred barrier endures — +3 rounds of protection.'),

    // ── WIZARD ──────────────────────────────────────────────────────────────
    AbilityRune(id: 'wiz_rune_1', name: 'Rune of Conflagration', classRequired: DndClass.wizard,
      abilityId: 'wiz_0', icon: '🔥', color: Color(0xFFff6633), dustCost: 15,
      valueMult: 1.5, durationAdd: 1, bonusEffectDesc: 'Fire Bolt: +50% damage, +1 burn round',
      description: 'Flames burn hotter and longer — 50% more, +1 burn.'),
    AbilityRune(id: 'wiz_rune_2', name: 'Rune of Frostbite', classRequired: DndClass.wizard,
      abilityId: 'wiz_2', icon: '❄', color: Color(0xFF44bbff), dustCost: 20,
      durationAdd: 2, cooldownReduce: 1, bonusEffectDesc: 'Frost Nova: +2 stun rounds, -1 cooldown',
      description: 'Freezing cold persists — +2 stun rounds, −1 cooldown.'),

    // ── SORCERER ────────────────────────────────────────────────────────────
    AbilityRune(id: 'sor_rune_1', name: 'Rune of Chaos', classRequired: DndClass.sorcerer,
      abilityId: 'sor_0', icon: '💥', color: Color(0xFFcc44ff), dustCost: 15,
      valueMult: 1.6, bonusEffectDesc: 'Arcane Blast deals 60% more damage',
      description: 'Wild magic surges — 60% more arcane damage.'),
    AbilityRune(id: 'sor_rune_2', name: 'Rune of the Void', classRequired: DndClass.sorcerer,
      abilityId: 'sor_3', icon: '🌑', color: Color(0xFF9944cc), dustCost: 20,
      durationAdd: 2, valueMult: 1.3, bonusEffectDesc: 'Void Bolt: +30% damage, +2 debuff rounds',
      description: 'Void energy lingers — +30% damage, +2 debuff duration.'),

    // ── WARLOCK ─────────────────────────────────────────────────────────────
    AbilityRune(id: 'wlk_rune_1', name: 'Rune of Agony', classRequired: DndClass.warlock,
      abilityId: 'wlk_0', icon: '☠', color: Color(0xFF9944cc), dustCost: 15,
      valueMult: 1.5, durationAdd: 2, bonusEffectDesc: 'Eldritch Blast: +50% damage, +2 DoT rounds',
      description: 'Cursed energy corrodes — +50% damage, +2 DoT rounds.'),
    AbilityRune(id: 'wlk_rune_2', name: 'Rune of Pact', classRequired: DndClass.warlock,
      abilityId: 'wlk_2', icon: '🔮', color: Color(0xFFaa66ff), dustCost: 20,
      valueMult: 1.4, cooldownReduce: 2, bonusEffectDesc: 'Dark Pact: +40% heal, -2 cooldown',
      description: 'Deeper pact — 40% stronger drain, faster recharge.'),

    // ── BARD ────────────────────────────────────────────────────────────────
    AbilityRune(id: 'brd_rune_1', name: 'Rune of Resonance', classRequired: DndClass.bard,
      abilityId: 'brd_1', icon: '🎵', color: Color(0xFFff88cc), dustCost: 15,
      durationAdd: 3, bonusEffectDesc: 'Inspiring Song lasts 3 extra rounds',
      description: 'The melody lingers — +3 rounds of inspiration.'),
    AbilityRune(id: 'brd_rune_2', name: 'Rune of Discord', classRequired: DndClass.bard,
      abilityId: 'brd_3', icon: '🔊', color: Color(0xFFcc66aa), dustCost: 20,
      valueMult: 1.5, durationAdd: 1, bonusEffectDesc: 'Discordant Note: +50% debuff, +1 round',
      description: 'Jarring discord — 50% stronger debuff, +1 duration.'),

    // ── MONK ────────────────────────────────────────────────────────────────
    AbilityRune(id: 'mnk_rune_1', name: 'Rune of Flow', classRequired: DndClass.monk,
      abilityId: 'mnk_0', icon: '☯', color: Color(0xFF88ddff), dustCost: 15,
      valueMult: 1.4, cooldownReduce: 1, bonusEffectDesc: 'Flurry of Blows: +40% damage, -1 cooldown',
      description: 'Flowing strikes — 40% more damage, faster recharge.'),
    AbilityRune(id: 'mnk_rune_2', name: 'Rune of Serenity', classRequired: DndClass.monk,
      abilityId: 'mnk_2', icon: '🧘', color: Color(0xFF66ccee), dustCost: 20,
      valueMult: 1.5, durationAdd: 2, bonusEffectDesc: 'Patient Defense: +50% dodge, +2 rounds',
      description: 'Inner calm deepens — 50% stronger dodge, +2 rounds.'),

    // ── DRUID ───────────────────────────────────────────────────────────────
    AbilityRune(id: 'drd_rune_1', name: 'Rune of Thorns', classRequired: DndClass.druid,
      abilityId: 'drd_0', icon: '🌿', color: Color(0xFF44aa66), dustCost: 15,
      valueMult: 1.5, durationAdd: 2, bonusEffectDesc: 'Entangle: +50% damage, +2 DoT rounds',
      description: 'Thorns dig deeper — 50% more damage, +2 poison rounds.'),
    AbilityRune(id: 'drd_rune_2', name: 'Rune of Regrowth', classRequired: DndClass.druid,
      abilityId: 'drd_2', icon: '🌱', color: Color(0xFF66dd88), dustCost: 20,
      valueMult: 1.4, durationAdd: 3, bonusEffectDesc: 'Rejuvenation: +40% heal, +3 regen rounds',
      description: 'Nature renews — 40% stronger heal, +3 regen rounds.'),

    // ══════════════════════════════════════════════════════════════════════════
    // EXPANDED RUNES — 8 more per class (abilities 2-6, ultimate, 2 general)
    // ══════════════════════════════════════════════════════════════════════════

    // ── BARBARIAN (expanded) ────────────────────────────────────────────────
    AbilityRune(id: 'barb_r3', name: 'Rune of Carnage', classRequired: DndClass.barbarian,
      abilityId: 'barbarian_2', icon: '💢', color: Color(0xFFee3333), dustCost: 18,
      valueMult: 1.4, durationAdd: 1, bonusEffectDesc: 'Battle Cry: +40% buff, +1 round',
      description: 'Warcry shakes the earth — stronger and longer.'),
    AbilityRune(id: 'barb_r4', name: 'Rune of Hellfire', classRequired: DndClass.barbarian,
      abilityId: 'barbarian_3', icon: '🔥', color: Color(0xFFff4400), dustCost: 18,
      valueMult: 1.5, bonusEffectDesc: 'Infernal Slam: +50% fire damage',
      description: 'Slam erupts in hellfire — 50% more damage.'),
    AbilityRune(id: 'barb_r5', name: 'Rune of the Berserker', classRequired: DndClass.barbarian,
      abilityId: 'barbarian_4', icon: '⚡', color: Color(0xFFff6622), dustCost: 22,
      cooldownReduce: 2, bonusEffectDesc: 'Bloodlust: -2 cooldown',
      description: 'Frenzy builds faster — recharge 2 rounds sooner.'),
    AbilityRune(id: 'barb_r6', name: 'Rune of Thunder', classRequired: DndClass.barbarian,
      abilityId: 'barbarian_5', icon: '⛈', color: Color(0xFFcc4411), dustCost: 22,
      valueMult: 1.6, bonusEffectDesc: 'Sundering Roar: +60% damage',
      description: 'Thunder splits armor — massive damage increase.'),
    AbilityRune(id: 'barb_r7', name: 'Rune of Rending', classRequired: DndClass.barbarian,
      abilityId: 'barbarian_6', icon: '🗡', color: Color(0xFFcc2200), dustCost: 20,
      valueMult: 1.3, durationAdd: 2, bonusEffectDesc: 'Rend: +30% bleed, +2 DoT rounds',
      description: 'Wounds tear deeper and bleed longer.'),
    AbilityRune(id: 'barb_r8', name: 'Rune of Wrath', classRequired: DndClass.barbarian,
      abilityId: 'barb_ult', icon: '💀', color: Color(0xFFdd0000), dustCost: 30,
      valueMult: 1.3, durationAdd: 1, bonusEffectDesc: 'Undying Rage: +30% dmg, +1 immune round',
      description: 'Ultimate rage burns brighter and lasts longer.'),
    AbilityRune(id: 'barb_r9', name: 'Rune of Iron Blood', classRequired: DndClass.barbarian,
      abilityId: 'barbarian_1', icon: '🩸', color: Color(0xFFaa1111), dustCost: 25,
      cooldownReduce: 1, valueMult: 1.2, bonusEffectDesc: 'All attacks: +20% dmg, -1 CD',
      description: 'Blood fuels every strike — faster, harder.'),
    AbilityRune(id: 'barb_r10', name: 'Rune of the Titan', classRequired: DndClass.barbarian,
      abilityId: 'barbarian_1', icon: '🏔', color: Color(0xFFbb3322), dustCost: 28,
      valueMult: 1.35, durationAdd: 1, bonusEffectDesc: 'Reckless Strike: +35% dmg, +1 dur',
      description: 'Strike with titanic force.'),

    // ── FIGHTER (expanded) ──────────────────────────────────────────────────
    AbilityRune(id: 'ftr_r3', name: 'Rune of Valor', classRequired: DndClass.fighter,
      abilityId: 'fighter_3', icon: '⚔', color: Color(0xFF7799dd), dustCost: 18,
      valueMult: 1.5, bonusEffectDesc: 'Cleave: +50% damage',
      description: 'Sweeping strikes cut deeper.'),
    AbilityRune(id: 'ftr_r4', name: 'Rune of Fortitude', classRequired: DndClass.fighter,
      abilityId: 'fighter_4', icon: '🛡', color: Color(0xFF5577cc), dustCost: 18,
      durationAdd: 3, bonusEffectDesc: 'Defensive Stance: +3 rounds',
      description: 'Hold the line longer.'),
    AbilityRune(id: 'ftr_r5', name: 'Rune of Mastery', classRequired: DndClass.fighter,
      abilityId: 'fighter_5', icon: '👑', color: Color(0xFF6688ee), dustCost: 22,
      valueMult: 1.4, cooldownReduce: 1, bonusEffectDesc: 'Whirlwind: +40% dmg, -1 CD',
      description: 'Spinning death accelerates.'),
    AbilityRune(id: 'ftr_r6', name: 'Rune of Execution', classRequired: DndClass.fighter,
      abilityId: 'fighter_6', icon: '⚡', color: Color(0xFF4466bb), dustCost: 22,
      valueMult: 1.6, bonusEffectDesc: 'Finishing Blow: +60% damage',
      description: 'The killing stroke strikes true.'),
    AbilityRune(id: 'ftr_r7', name: 'Rune of the Champion', classRequired: DndClass.fighter,
      abilityId: 'ftr_ult', icon: '🏆', color: Color(0xFF88aaff), dustCost: 30,
      valueMult: 1.3, durationAdd: 2, bonusEffectDesc: 'Blade Storm: +30% dmg, +2 strikes',
      description: 'The ultimate warrior unleashes more.'),
    AbilityRune(id: 'ftr_r8', name: 'Rune of Discipline', classRequired: DndClass.fighter,
      abilityId: 'fighter_1', icon: '🎖', color: Color(0xFF99bbff), dustCost: 25,
      cooldownReduce: 1, bonusEffectDesc: 'Power Strike: -1 cooldown',
      description: 'Trained reflexes shorten the gap.'),
    AbilityRune(id: 'ftr_r9', name: 'Rune of Steel', classRequired: DndClass.fighter,
      abilityId: 'fighter_2', icon: '⚙', color: Color(0xFF7788cc), dustCost: 20,
      valueMult: 1.3, durationAdd: 1, bonusEffectDesc: 'Second Wind: +30% heal, +1 regen',
      description: 'Steel resolve heals deeper.'),
    AbilityRune(id: 'ftr_r10', name: 'Rune of the Warlord', classRequired: DndClass.fighter,
      abilityId: 'fighter_1', icon: '🗡', color: Color(0xFF6699ff), dustCost: 28,
      valueMult: 1.5, bonusEffectDesc: 'Power Strike: +50% total damage',
      description: 'Command the battlefield with devastating force.'),

    // ── ROGUE (expanded) ────────────────────────────────────────────────────
    AbilityRune(id: 'rog_r3', name: 'Rune of Venom', classRequired: DndClass.rogue,
      abilityId: 'rogue_3', icon: '☠', color: Color(0xFF44aa66), dustCost: 18,
      valueMult: 1.5, durationAdd: 2, bonusEffectDesc: 'Poison Blade: +50% dmg, +2 DoT',
      description: 'Deadlier poison lingers.'),
    AbilityRune(id: 'rog_r4', name: 'Rune of Cunning', classRequired: DndClass.rogue,
      abilityId: 'rogue_4', icon: '🃏', color: Color(0xFF33cc77), dustCost: 18,
      cooldownReduce: 2, bonusEffectDesc: 'Cheap Shot: -2 cooldown',
      description: 'Dirty tricks come faster.'),
    AbilityRune(id: 'rog_r5', name: 'Rune of Lethality', classRequired: DndClass.rogue,
      abilityId: 'rogue_5', icon: '💀', color: Color(0xFF22aa55), dustCost: 22,
      valueMult: 1.7, bonusEffectDesc: 'Assassinate: +70% damage',
      description: 'One perfect strike to end it all.'),
    AbilityRune(id: 'rog_r6', name: 'Rune of Evasion', classRequired: DndClass.rogue,
      abilityId: 'rogue_6', icon: '💨', color: Color(0xFF55cc99), dustCost: 22,
      durationAdd: 3, bonusEffectDesc: 'Smoke Bomb: +3 dodge rounds',
      description: 'Smoke lingers — untouchable longer.'),
    AbilityRune(id: 'rog_r7', name: 'Rune of the Phantom', classRequired: DndClass.rogue,
      abilityId: 'rog_ult', icon: '👻', color: Color(0xFF44dd88), dustCost: 30,
      valueMult: 1.4, durationAdd: 1, bonusEffectDesc: 'Death Mark: +40% crit dmg, +1 round',
      description: 'The mark burns brighter and lasts longer.'),
    AbilityRune(id: 'rog_r8', name: 'Rune of Precision', classRequired: DndClass.rogue,
      abilityId: 'rogue_2', icon: '🎯', color: Color(0xFF66ee99), dustCost: 25,
      valueMult: 1.3, bonusEffectDesc: 'Sneak Attack: +30% damage',
      description: 'Surgical precision — every hit counts more.'),
    AbilityRune(id: 'rog_r9', name: 'Rune of Subtlety', classRequired: DndClass.rogue,
      abilityId: 'rogue_1', icon: '🌙', color: Color(0xFF33bb66), dustCost: 20,
      cooldownReduce: 1, durationAdd: 1, bonusEffectDesc: 'Shadow Step: -1 CD, +1 stealth',
      description: 'Move unseen, strike without warning.'),
    AbilityRune(id: 'rog_r10', name: 'Rune of the Nightblade', classRequired: DndClass.rogue,
      abilityId: 'rogue_1', icon: '🗡', color: Color(0xFF22cc88), dustCost: 28,
      valueMult: 1.5, cooldownReduce: 1, bonusEffectDesc: 'Backstab: +50% dmg, -1 CD',
      description: 'The night itself strikes with you.'),

    // ── RANGER (expanded) ───────────────────────────────────────────────────
    AbilityRune(id: 'rng_r3', name: 'Rune of the Eagle', classRequired: DndClass.ranger,
      abilityId: 'ranger_3', icon: '🦅', color: Color(0xFF88cc55), dustCost: 18,
      valueMult: 1.4, bonusEffectDesc: 'Volley: +40% damage', description: 'Eagle-eyed volleys hit harder.'),
    AbilityRune(id: 'rng_r4', name: 'Rune of Trapping', classRequired: DndClass.ranger,
      abilityId: 'ranger_4', icon: '🪤', color: Color(0xFF77aa33), dustCost: 18,
      durationAdd: 2, bonusEffectDesc: 'Trap: +2 stun rounds', description: 'Traps hold prey longer.'),
    AbilityRune(id: 'rng_r5', name: 'Rune of the Wild', classRequired: DndClass.ranger,
      abilityId: 'ranger_5', icon: '🐺', color: Color(0xFF66bb44), dustCost: 22,
      valueMult: 1.5, cooldownReduce: 1, bonusEffectDesc: 'Companion: +50% dmg, -1 CD', description: 'Beast companion strikes with fury.'),
    AbilityRune(id: 'rng_r6', name: 'Rune of Barrage', classRequired: DndClass.ranger,
      abilityId: 'ranger_6', icon: '🏹', color: Color(0xFF55aa22), dustCost: 22,
      valueMult: 1.6, bonusEffectDesc: 'Hail of Arrows: +60% damage', description: 'A storm of arrows blankets the field.'),
    AbilityRune(id: 'rng_r7', name: 'Rune of the Tempest', classRequired: DndClass.ranger,
      abilityId: 'rng_ult', icon: '🌧', color: Color(0xFF44aa33), dustCost: 30,
      valueMult: 1.3, durationAdd: 2, bonusEffectDesc: 'Arrow Rain: +30% dmg, +2 DoT rounds', description: 'The storm rages longer.'),
    AbilityRune(id: 'rng_r8', name: 'Rune of Stalking', classRequired: DndClass.ranger,
      abilityId: 'ranger_1', icon: '👁', color: Color(0xFF99cc66), dustCost: 25,
      valueMult: 1.35, bonusEffectDesc: 'Aimed Shot: +35% damage', description: 'Patient aim yields deadlier shots.'),
    AbilityRune(id: 'rng_r9', name: 'Rune of Nature', classRequired: DndClass.ranger,
      abilityId: 'ranger_2', icon: '🌿', color: Color(0xFF77bb55), dustCost: 20,
      durationAdd: 3, bonusEffectDesc: 'Poison Shot: +3 DoT rounds', description: 'Natural toxins persist.'),
    AbilityRune(id: 'rng_r10', name: 'Rune of the Apex', classRequired: DndClass.ranger,
      abilityId: 'ranger_1', icon: '🎯', color: Color(0xFF88dd44), dustCost: 28,
      valueMult: 1.6, cooldownReduce: 1, bonusEffectDesc: 'Aimed Shot: +60% dmg, -1 CD', description: 'Apex predator — devastating and relentless.'),

    // ── PALADIN (expanded) ──────────────────────────────────────────────────
    AbilityRune(id: 'pal_r3', name: 'Rune of Zeal', classRequired: DndClass.paladin,
      abilityId: 'paladin_3', icon: '⚔', color: Color(0xFFeecc22), dustCost: 18,
      valueMult: 1.5, bonusEffectDesc: 'Zealous Strike: +50% holy dmg', description: 'Strike with divine fury.'),
    AbilityRune(id: 'pal_r4', name: 'Rune of Protection', classRequired: DndClass.paladin,
      abilityId: 'paladin_4', icon: '🛡', color: Color(0xFFddbb33), dustCost: 18,
      durationAdd: 3, bonusEffectDesc: 'Divine Shield: +3 rounds', description: 'Sacred barrier endures.'),
    AbilityRune(id: 'pal_r5', name: 'Rune of Wrath', classRequired: DndClass.paladin,
      abilityId: 'paladin_5', icon: '⚡', color: Color(0xFFffdd44), dustCost: 22,
      valueMult: 1.6, bonusEffectDesc: 'Holy Wrath: +60% damage', description: 'Righteous fury overwhelms evil.'),
    AbilityRune(id: 'pal_r6', name: 'Rune of Aura', classRequired: DndClass.paladin,
      abilityId: 'paladin_6', icon: '✨', color: Color(0xFFccaa11), dustCost: 22,
      durationAdd: 2, valueMult: 1.3, bonusEffectDesc: 'Aura: +30% effect, +2 rounds', description: 'Holy aura burns brighter.'),
    AbilityRune(id: 'pal_r7', name: 'Rune of Judgement', classRequired: DndClass.paladin,
      abilityId: 'pal_ult', icon: '👑', color: Color(0xFFffcc00), dustCost: 30,
      valueMult: 1.4, bonusEffectDesc: 'Divine Judgement: +40% damage + full heal', description: 'Heaven\'s judgement falls heavier.'),
    AbilityRune(id: 'pal_r8', name: 'Rune of Light', classRequired: DndClass.paladin,
      abilityId: 'paladin_1', icon: '☀', color: Color(0xFFffee55), dustCost: 25,
      valueMult: 1.3, cooldownReduce: 1, bonusEffectDesc: 'Smite: +30% dmg, -1 CD', description: 'Light strikes faster.'),
    AbilityRune(id: 'pal_r9', name: 'Rune of Mercy', classRequired: DndClass.paladin,
      abilityId: 'paladin_2', icon: '💛', color: Color(0xFFddcc44), dustCost: 20,
      valueMult: 1.5, bonusEffectDesc: 'Lay on Hands: +50% heal', description: 'Merciful hands heal more.'),
    AbilityRune(id: 'pal_r10', name: 'Rune of the Crusader', classRequired: DndClass.paladin,
      abilityId: 'paladin_1', icon: '✦', color: Color(0xFFeecc00), dustCost: 28,
      valueMult: 1.5, durationAdd: 1, bonusEffectDesc: 'Smite: +50% dmg, +1 holy burn', description: 'Crusader\'s strike sears with light.'),

    // ── CLERIC (expanded) ───────────────────────────────────────────────────
    AbilityRune(id: 'clr_r3', name: 'Rune of Smiting', classRequired: DndClass.cleric,
      abilityId: 'cleric_3', icon: '⚡', color: Color(0xFFffaacc), dustCost: 18,
      valueMult: 1.5, bonusEffectDesc: 'Sacred Flame: +50% damage', description: 'Holy fire burns the unholy.'),
    AbilityRune(id: 'clr_r4', name: 'Rune of Renewal', classRequired: DndClass.cleric,
      abilityId: 'cleric_4', icon: '🌿', color: Color(0xFFffccdd), dustCost: 18,
      durationAdd: 3, valueMult: 1.3, bonusEffectDesc: 'Regeneration: +30% heal, +3 rounds', description: 'Sustained healing over time.'),
    AbilityRune(id: 'clr_r5', name: 'Rune of Banishment', classRequired: DndClass.cleric,
      abilityId: 'cleric_5', icon: '✝', color: Color(0xFFee99bb), dustCost: 22,
      valueMult: 1.6, bonusEffectDesc: 'Turn Undead: +60% damage', description: 'Undead flee before divine power.'),
    AbilityRune(id: 'clr_r6', name: 'Rune of Mass Heal', classRequired: DndClass.cleric,
      abilityId: 'cleric_6', icon: '❤', color: Color(0xFFdd88aa), dustCost: 22,
      valueMult: 1.4, durationAdd: 2, bonusEffectDesc: 'Prayer: +40% heal, +2 regen', description: 'Prayers reach deeper into the soul.'),
    AbilityRune(id: 'clr_r7', name: 'Rune of the Miracle', classRequired: DndClass.cleric,
      abilityId: 'clr_ult', icon: '🌟', color: Color(0xFFffbbdd), dustCost: 30,
      valueMult: 1.3, durationAdd: 2, bonusEffectDesc: 'Miracle: +30% heal, +2 regen rounds', description: 'The ultimate miracle endures.'),
    AbilityRune(id: 'clr_r8', name: 'Rune of Faith', classRequired: DndClass.cleric,
      abilityId: 'cleric_1', icon: '🕊', color: Color(0xFFffddee), dustCost: 25,
      valueMult: 1.4, bonusEffectDesc: 'Heal Word: +40% HP restored', description: 'Unwavering faith amplifies healing.'),
    AbilityRune(id: 'clr_r9', name: 'Rune of the Bastion', classRequired: DndClass.cleric,
      abilityId: 'cleric_3', icon: '🏰', color: Color(0xFFcc88aa), dustCost: 20,
      durationAdd: 2, cooldownReduce: 1, bonusEffectDesc: 'Shield: +2 dur, -1 CD', description: 'The shield of faith holds firm.'),
    AbilityRune(id: 'clr_r10', name: 'Rune of the Archon', classRequired: DndClass.cleric,
      abilityId: 'cleric_1', icon: '👼', color: Color(0xFFffaadd), dustCost: 28,
      valueMult: 1.6, cooldownReduce: 1, bonusEffectDesc: 'Heal Word: +60% HP, -1 CD', description: 'Archon\'s blessing — divine healing unmatched.'),

    // ── WIZARD (expanded) ───────────────────────────────────────────────────
    AbilityRune(id: 'wiz_r3', name: 'Rune of Lightning', classRequired: DndClass.wizard,
      abilityId: 'wizard_3', icon: '⚡', color: Color(0xFFffcc00), dustCost: 18,
      valueMult: 1.5, bonusEffectDesc: 'Chain Lightning: +50% damage', description: 'Lightning arcs with greater force.'),
    AbilityRune(id: 'wiz_r4', name: 'Rune of Shielding', classRequired: DndClass.wizard,
      abilityId: 'wizard_4', icon: '🔷', color: Color(0xFF3399ff), dustCost: 18,
      durationAdd: 3, bonusEffectDesc: 'Arcane Shield: +3 rounds', description: 'Arcane barrier persists.'),
    AbilityRune(id: 'wiz_r5', name: 'Rune of Disintegration', classRequired: DndClass.wizard,
      abilityId: 'wizard_5', icon: '💥', color: Color(0xFFff5500), dustCost: 22,
      valueMult: 1.7, bonusEffectDesc: 'Disintegrate: +70% damage', description: 'Matter itself unravels.'),
    AbilityRune(id: 'wiz_r6', name: 'Rune of Time', classRequired: DndClass.wizard,
      abilityId: 'wizard_6', icon: '⏳', color: Color(0xFF66aaff), dustCost: 22,
      cooldownReduce: 2, bonusEffectDesc: 'Time Warp: -2 cooldown on all', description: 'Bend time to cast faster.'),
    AbilityRune(id: 'wiz_r7', name: 'Rune of Cataclysm', classRequired: DndClass.wizard,
      abilityId: 'wiz_ult', icon: '☄', color: Color(0xFFff8833), dustCost: 30,
      valueMult: 1.4, durationAdd: 2, bonusEffectDesc: 'Meteor: +40% dmg, +2 burn rounds', description: 'Apocalyptic meteor burns everything.'),
    AbilityRune(id: 'wiz_r8', name: 'Rune of Amplification', classRequired: DndClass.wizard,
      abilityId: 'wizard_1', icon: '🔮', color: Color(0xFF88bbff), dustCost: 25,
      valueMult: 1.3, bonusEffectDesc: 'Fire Bolt: +30% damage', description: 'Amplified arcane energy.'),
    AbilityRune(id: 'wiz_r9', name: 'Rune of Permafrost', classRequired: DndClass.wizard,
      abilityId: 'wizard_2', icon: '🧊', color: Color(0xFF33aaff), dustCost: 20,
      durationAdd: 2, valueMult: 1.2, bonusEffectDesc: 'Frost Nova: +20% dmg, +2 freeze', description: 'Absolute zero encases foes.'),
    AbilityRune(id: 'wiz_r10', name: 'Rune of the Archmage', classRequired: DndClass.wizard,
      abilityId: 'wizard_1', icon: '🌟', color: Color(0xFF5599ff), dustCost: 28,
      valueMult: 1.6, cooldownReduce: 1, bonusEffectDesc: 'Fire Bolt: +60% dmg, -1 CD', description: 'The archmage commands elemental fury.'),

    // ── SORCERER (expanded) ─────────────────────────────────────────────────
    AbilityRune(id: 'sor_r3', name: 'Rune of Surge', classRequired: DndClass.sorcerer,
      abilityId: 'sorcerer_3', icon: '💫', color: Color(0xFFbb44ee), dustCost: 18,
      valueMult: 1.5, bonusEffectDesc: 'Wild Surge: +50% damage', description: 'Magic surges uncontrollably.'),
    AbilityRune(id: 'sor_r4', name: 'Rune of Metamagic', classRequired: DndClass.sorcerer,
      abilityId: 'sorcerer_4', icon: '✨', color: Color(0xFFaa33dd), dustCost: 18,
      cooldownReduce: 2, bonusEffectDesc: 'Quicken: -2 CD on ability', description: 'Metamagic accelerates casting.'),
    AbilityRune(id: 'sor_r5', name: 'Rune of Annihilation', classRequired: DndClass.sorcerer,
      abilityId: 'sorcerer_5', icon: '🌀', color: Color(0xFFdd55ff), dustCost: 22,
      valueMult: 1.7, bonusEffectDesc: 'Void Rift: +70% damage', description: 'Reality tears apart.'),
    AbilityRune(id: 'sor_r6', name: 'Rune of Empowerment', classRequired: DndClass.sorcerer,
      abilityId: 'sorcerer_6', icon: '⚡', color: Color(0xFF9933cc), dustCost: 22,
      valueMult: 1.4, durationAdd: 2, bonusEffectDesc: 'Empower: +40% buff, +2 rounds', description: 'Raw magic empowers beyond limits.'),
    AbilityRune(id: 'sor_r7', name: 'Rune of the Singularity', classRequired: DndClass.sorcerer,
      abilityId: 'sor_ult', icon: '🕳', color: Color(0xFFcc55ff), dustCost: 30,
      valueMult: 1.3, durationAdd: 1, bonusEffectDesc: 'Singularity: +30% dmg, +1 stun', description: 'The void consumes all.'),
    AbilityRune(id: 'sor_r8', name: 'Rune of Instability', classRequired: DndClass.sorcerer,
      abilityId: 'sorcerer_1', icon: '🎆', color: Color(0xFFee66ff), dustCost: 25,
      valueMult: 1.4, bonusEffectDesc: 'Arcane Blast: +40% damage', description: 'Unstable magic hits harder.'),
    AbilityRune(id: 'sor_r9', name: 'Rune of Entropy', classRequired: DndClass.sorcerer,
      abilityId: 'sorcerer_3', icon: '🌑', color: Color(0xFFaa44cc), dustCost: 20,
      durationAdd: 2, bonusEffectDesc: 'Void Bolt: +2 debuff rounds', description: 'Entropy spreads further.'),
    AbilityRune(id: 'sor_r10', name: 'Rune of the Wild Mage', classRequired: DndClass.sorcerer,
      abilityId: 'sorcerer_1', icon: '🃏', color: Color(0xFFdd44ff), dustCost: 28,
      valueMult: 1.6, cooldownReduce: 1, bonusEffectDesc: 'Arcane Blast: +60% dmg, -1 CD', description: 'Wild magic bends to your will.'),

    // ── WARLOCK (expanded) ──────────────────────────────────────────────────
    AbilityRune(id: 'wlk_r3', name: 'Rune of Corruption', classRequired: DndClass.warlock,
      abilityId: 'warlock_3', icon: '🦠', color: Color(0xFF8833bb), dustCost: 18,
      valueMult: 1.5, durationAdd: 2, bonusEffectDesc: 'Corruption: +50% dmg, +2 DoT', description: 'Foul magic corrupts deeper.'),
    AbilityRune(id: 'wlk_r4', name: 'Rune of Dread', classRequired: DndClass.warlock,
      abilityId: 'warlock_4', icon: '😱', color: Color(0xFF7722aa), dustCost: 18,
      durationAdd: 3, bonusEffectDesc: 'Fear: +3 debuff rounds', description: 'Terror grips the soul longer.'),
    AbilityRune(id: 'wlk_r5', name: 'Rune of Damnation', classRequired: DndClass.warlock,
      abilityId: 'warlock_5', icon: '🔥', color: Color(0xFFaa44dd), dustCost: 22,
      valueMult: 1.6, bonusEffectDesc: 'Hellfire: +60% damage', description: 'Infernal flames consume all.'),
    AbilityRune(id: 'wlk_r6', name: 'Rune of the Abyss', classRequired: DndClass.warlock,
      abilityId: 'warlock_6', icon: '🌑', color: Color(0xFF6611aa), dustCost: 22,
      valueMult: 1.5, cooldownReduce: 1, bonusEffectDesc: 'Abyssal Gate: +50% dmg, -1 CD', description: 'The abyss answers faster.'),
    AbilityRune(id: 'wlk_r7', name: 'Rune of Soul Reaping', classRequired: DndClass.warlock,
      abilityId: 'wlk_ult', icon: '💀', color: Color(0xFFbb55ee), dustCost: 30,
      valueMult: 1.4, bonusEffectDesc: 'Soul Harvest: +40% drain + heal', description: 'Reap more from the dying.'),
    AbilityRune(id: 'wlk_r8', name: 'Rune of Binding', classRequired: DndClass.warlock,
      abilityId: 'warlock_1', icon: '⛓', color: Color(0xFFcc66ff), dustCost: 25,
      valueMult: 1.3, durationAdd: 1, bonusEffectDesc: 'Eldritch Blast: +30% dmg, +1 DoT', description: 'Chains of eldritch energy bind tighter.'),
    AbilityRune(id: 'wlk_r9', name: 'Rune of Dark Pact', classRequired: DndClass.warlock,
      abilityId: 'warlock_2', icon: '📜', color: Color(0xFF9944dd), dustCost: 20,
      valueMult: 1.5, cooldownReduce: 1, bonusEffectDesc: 'Dark Pact: +50% drain, -1 CD', description: 'The pact deepens.'),
    AbilityRune(id: 'wlk_r10', name: 'Rune of the Dark Lord', classRequired: DndClass.warlock,
      abilityId: 'warlock_1', icon: '👑', color: Color(0xFFaa33cc), dustCost: 28,
      valueMult: 1.6, durationAdd: 2, bonusEffectDesc: 'Eldritch Blast: +60% dmg, +2 DoT', description: 'Command darkness itself.'),

    // ── BARD (expanded) ─────────────────────────────────────────────────────
    AbilityRune(id: 'brd_r3', name: 'Rune of Harmony', classRequired: DndClass.bard,
      abilityId: 'bard_3', icon: '🎶', color: Color(0xFFdd77bb), dustCost: 18,
      valueMult: 1.4, durationAdd: 2, bonusEffectDesc: 'Harmony: +40% buff, +2 rounds', description: 'Perfect harmony inspires longer.'),
    AbilityRune(id: 'brd_r4', name: 'Rune of Cacophony', classRequired: DndClass.bard,
      abilityId: 'bard_4', icon: '📯', color: Color(0xFFcc66aa), dustCost: 18,
      valueMult: 1.5, bonusEffectDesc: 'Shatter: +50% sonic damage', description: 'Sound waves shatter everything.'),
    AbilityRune(id: 'brd_r5', name: 'Rune of Enchantment', classRequired: DndClass.bard,
      abilityId: 'bard_5', icon: '💝', color: Color(0xFFee88cc), dustCost: 22,
      durationAdd: 3, bonusEffectDesc: 'Charm: +3 debuff rounds', description: 'Enchanting melody captivates longer.'),
    AbilityRune(id: 'brd_r6', name: 'Rune of the Crescendo', classRequired: DndClass.bard,
      abilityId: 'bard_6', icon: '🎼', color: Color(0xFFbb5599), dustCost: 22,
      valueMult: 1.6, cooldownReduce: 1, bonusEffectDesc: 'Finale: +60% dmg, -1 CD', description: 'The grand finale arrives sooner.'),
    AbilityRune(id: 'brd_r7', name: 'Rune of the Virtuoso', classRequired: DndClass.bard,
      abilityId: 'brd_ult', icon: '🎭', color: Color(0xFFff99dd), dustCost: 30,
      valueMult: 1.3, durationAdd: 2, bonusEffectDesc: 'Crescendo: +30% stats, +2 rounds', description: 'The masterpiece endures.'),
    AbilityRune(id: 'brd_r8', name: 'Rune of Melody', classRequired: DndClass.bard,
      abilityId: 'bard_2', icon: '🎵', color: Color(0xFFee77cc), dustCost: 25,
      valueMult: 1.4, bonusEffectDesc: 'Healing Song: +40% heal', description: 'Soothing melodies restore more.'),
    AbilityRune(id: 'brd_r9', name: 'Rune of Mockery', classRequired: DndClass.bard,
      abilityId: 'bard_3', icon: '😏', color: Color(0xFFdd66aa), dustCost: 20,
      durationAdd: 2, cooldownReduce: 1, bonusEffectDesc: 'Discordant Note: +2 dur, -1 CD', description: 'Vicious mockery that lingers.'),
    AbilityRune(id: 'brd_r10', name: 'Rune of the Maestro', classRequired: DndClass.bard,
      abilityId: 'bard_1', icon: '🎻', color: Color(0xFFff88dd), dustCost: 28,
      durationAdd: 4, bonusEffectDesc: 'Inspiring Song: +4 rounds', description: 'The maestro\'s song never fades.'),

    // ── MONK (expanded) ─────────────────────────────────────────────────────
    AbilityRune(id: 'mnk_r3', name: 'Rune of Ki', classRequired: DndClass.monk,
      abilityId: 'monk_3', icon: '🔵', color: Color(0xFF55ccee), dustCost: 18,
      valueMult: 1.5, bonusEffectDesc: 'Ki Strike: +50% damage', description: 'Focused ki empowers the strike.'),
    AbilityRune(id: 'mnk_r4', name: 'Rune of Wind', classRequired: DndClass.monk,
      abilityId: 'monk_4', icon: '🌪', color: Color(0xFF44bbdd), dustCost: 18,
      cooldownReduce: 2, bonusEffectDesc: 'Step of Wind: -2 cooldown', description: 'Move like the wind itself.'),
    AbilityRune(id: 'mnk_r5', name: 'Rune of Iron Fist', classRequired: DndClass.monk,
      abilityId: 'monk_5', icon: '✊', color: Color(0xFF66ddff), dustCost: 22,
      valueMult: 1.6, bonusEffectDesc: 'Stunning Fist: +60% damage', description: 'Iron fists shatter stone.'),
    AbilityRune(id: 'mnk_r6', name: 'Rune of Tranquility', classRequired: DndClass.monk,
      abilityId: 'monk_6', icon: '🧘', color: Color(0xFF33aacc), dustCost: 22,
      valueMult: 1.4, durationAdd: 2, bonusEffectDesc: 'Meditation: +40% heal, +2 regen', description: 'Deep meditation heals body and spirit.'),
    AbilityRune(id: 'mnk_r7', name: 'Rune of the Dragon', classRequired: DndClass.monk,
      abilityId: 'mnk_ult', icon: '🐉', color: Color(0xFF88eeff), dustCost: 30,
      valueMult: 1.3, durationAdd: 3, bonusEffectDesc: 'Thousand Fists: +30% dmg, +3 strikes', description: 'Dragon spirit unleashes more strikes.'),
    AbilityRune(id: 'mnk_r8', name: 'Rune of Swiftness', classRequired: DndClass.monk,
      abilityId: 'monk_1', icon: '⚡', color: Color(0xFF77ddee), dustCost: 25,
      cooldownReduce: 1, valueMult: 1.2, bonusEffectDesc: 'Flurry: -1 CD, +20% dmg', description: 'Lightning-fast combinations.'),
    AbilityRune(id: 'mnk_r9', name: 'Rune of Balance', classRequired: DndClass.monk,
      abilityId: 'monk_2', icon: '⚖', color: Color(0xFF55bbcc), dustCost: 20,
      durationAdd: 3, bonusEffectDesc: 'Patient Defense: +3 dodge rounds', description: 'Perfect balance grants evasion.'),
    AbilityRune(id: 'mnk_r10', name: 'Rune of the Grandmaster', classRequired: DndClass.monk,
      abilityId: 'monk_1', icon: '🥋', color: Color(0xFF66ccdd), dustCost: 28,
      valueMult: 1.5, cooldownReduce: 1, bonusEffectDesc: 'Flurry: +50% dmg, -1 CD', description: 'Grandmaster technique — devastation.'),

    // ── DRUID (expanded) ────────────────────────────────────────────────────
    AbilityRune(id: 'drd_r3', name: 'Rune of the Storm', classRequired: DndClass.druid,
      abilityId: 'druid_3', icon: '⛈', color: Color(0xFF33aa55), dustCost: 18,
      valueMult: 1.5, bonusEffectDesc: 'Call Lightning: +50% damage', description: 'Nature\'s wrath strikes harder.'),
    AbilityRune(id: 'drd_r4', name: 'Rune of Bark', classRequired: DndClass.druid,
      abilityId: 'druid_4', icon: '🌳', color: Color(0xFF55bb66), dustCost: 18,
      durationAdd: 3, bonusEffectDesc: 'Barkskin: +3 armor rounds', description: 'Ancient bark hardens further.'),
    AbilityRune(id: 'drd_r5', name: 'Rune of the Moon', classRequired: DndClass.druid,
      abilityId: 'druid_5', icon: '🌙', color: Color(0xFF44cc77), dustCost: 22,
      valueMult: 1.6, bonusEffectDesc: 'Moonbeam: +60% damage', description: 'Lunar energy intensifies.'),
    AbilityRune(id: 'drd_r6', name: 'Rune of Wildshape', classRequired: DndClass.druid,
      abilityId: 'druid_6', icon: '🐻', color: Color(0xFF66dd88), dustCost: 22,
      valueMult: 1.4, durationAdd: 2, bonusEffectDesc: 'Wildshape: +40% stats, +2 rounds', description: 'Beast form grows stronger.'),
    AbilityRune(id: 'drd_r7', name: 'Rune of the Primal', classRequired: DndClass.druid,
      abilityId: 'drd_ult', icon: '🦁', color: Color(0xFF88ee99), dustCost: 30,
      valueMult: 1.3, durationAdd: 2, bonusEffectDesc: 'Primal Avatar: +30% stats, +2 rounds', description: 'The primal form endures.'),
    AbilityRune(id: 'drd_r8', name: 'Rune of Growth', classRequired: DndClass.druid,
      abilityId: 'druid_1', icon: '🌱', color: Color(0xFF77ee88), dustCost: 25,
      valueMult: 1.3, durationAdd: 1, bonusEffectDesc: 'Entangle: +30% dmg, +1 DoT', description: 'Nature grows relentlessly.'),
    AbilityRune(id: 'drd_r9', name: 'Rune of Life', classRequired: DndClass.druid,
      abilityId: 'druid_2', icon: '💚', color: Color(0xFF55cc66), dustCost: 20,
      valueMult: 1.5, bonusEffectDesc: 'Rejuvenation: +50% heal', description: 'Life force surges through you.'),
    AbilityRune(id: 'drd_r10', name: 'Rune of the World Tree', classRequired: DndClass.druid,
      abilityId: 'druid_2', icon: '🌍', color: Color(0xFF44bb55), dustCost: 28,
      valueMult: 1.5, durationAdd: 3, bonusEffectDesc: 'Rejuvenation: +50% heal, +3 regen', description: 'The World Tree\'s blessing — eternal renewal.'),
  ];

  static List<AbilityRune> forClass(DndClass cls) =>
      all.where((r) => r.classRequired == cls).toList();
}
